assembly-versioning-scheme: MajorMinorPatch
mode: ManualDeployment
next-version: 0.0.1
branches:
  main:
    mode: ContinuousDelivery
    increment: Patch
    tracks-release-branches: true
    regex: ^master$|^main$
    label: Preview
    is-main-branch: true
    prevent-increment:
      of-merged-branch: false
  release:
    mode: ManualDeployment
    increment: Patch
    track-merge-target: false
    regex: ^release(s)?[\/-]
    source-branches:
    - main
    is-release-branch: true
    label: ""
    is-main-branch: false
ignore:
  sha: []
merge-message-formats: {}
commit-message-incrementing: Enabled
