# This workflow is managed by gh actions-lock.

name: GuideSite Close PR
on:
  workflow_call:
    secrets:
      static-web-app-token:
        required: true
permissions:
  contents: read
  pull-requests: write
jobs:
  close:
    name: Close PR preview
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Azure PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.static-web-app-token }}
          repo_token: ${{ github.token }}
          action: close
          deployment_environment: ${{ github.event.pull_request.number }}
          app_location: ''
          skip_app_build: true
          skip_api_build: true
